plugins {
    id 'com.android.application'
}

android {
    namespace 'com.unb.imageeditor'
    compileSdk 35

    defaultConfig {
        applicationId "com.unb.imageeditor"
        minSdk 26
        targetSdk 35
        versionCode 24
        versionName "1.1.0-alpha-offline"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
}
